export const appearance = {
    colorAction: '#5E48FC',
    colorBackground: '#0A0A0C',
    colorBorder: '#68686C',
    colorDisabled: '#64646E',
    colorError: '#FF3300',
    colorFormBackground: '#1F1F1F',
    colorFormBorder: '#1F1F1F',
    colorInverse: '#F9F9FB',
    colorOutline: '#ADA4EC',
    colorPrimary: '#F9F9FB',
    colorSecondary: '#828388',
    colorSuccess: '#2ECC71',
    button: {
      fontFamily: '"Roboto Mono", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 700,
      letterSpacing: 0,
      lineHeight: '24px',
    },
    footnote: {
      fontFamily: '"PT Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: '20px',
    },
    label: {
      fontFamily: '"Roboto Mono", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif',
      fontSize: '14px',
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: '20px',
    },
    subheading: {
      fontFamily: '"Roboto Mono", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", "Noto Sans", "Liberation Sans", Arial, sans-serif',
      fontSize: '16px',
      fontWeight: 700,
      letterSpacing: 0,
      lineHeight: '24px',
    },
    borderRadius: ['8px', '8px'],
  };